CREATE TABLE USERS (
	id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
	name VARCHAR(64) NOT NULL UNIQUE,
    hashed_password VARCHAR(128) NOT NULL
);

CREATE TABLE CLASSES (
	id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
	name VARCHAR(64) NOT NULL,
    semester VARCHAR(32) NOT NULL,
    year YEAR(4)
);

CREATE TABLE QUESTIONS (
	id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
    class_id INTEGER NOT NULL REFERENCES CLASSES(id) ON DELETE RESTRICT,
    user_id INTEGER NOT NULL REFERENCES USERS(id) ON DELETE RESTRICT,
	content VARCHAR(256) NOT NULL,
    created_at DATETIME
);

CREATE TABLE ANSWERS (
	id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
    question_id INTEGER NOT NULL REFERENCES QUESTIONS(id) ON DELETE RESTRICT,
    user_id INTEGER NOT NULL REFERENCES USERS(id) ON DELETE RESTRICT,
	content VARCHAR(256) NOT NULL,
    created_at DATETIME
);